In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from 'C:\\Users\\neo\\Anaconda3\\envs\\my1\\lib\\site-packages\\numpy\\__init__.py'>

# Горячие клавиши
Ctrl+Enter — выполнение текущей ячейки и сохранение фокуса на текущей ячейке. 

Alt+Enter — выполнение текущей ячейки и перевод фокуса на новую ячейку созданную ниже.

In [3]:
num_array=np.array([1, 2, 3, 4])
num_array

array([1, 2, 3, 4])

In [4]:
type(num_array)

numpy.ndarray

In [5]:
num_array[0]

1

In [6]:
num_array[-1]

4

In [7]:
num_array.shape

(4,)

In [8]:
num_array.ndim

1

In [9]:
num_array.size

4

In [10]:
num_array.dtype

dtype('int32')

In [11]:
num_array.itemsize

4

In [12]:
340


340

## Python NUMPY - Полный Курс для Начинающих

In [13]:
my_list=[4, 25, 44, 30, 8]

In [14]:
m=np.array(my_list)
m

array([ 4, 25, 44, 30,  8])

In [15]:
m*10

array([ 40, 250, 440, 300,  80])

In [16]:
m+100

array([104, 125, 144, 130, 108])

In [21]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])